DROP TABLE "BLOCKINDEX"."BLOCKINDEX" CASCADE CONSTRAINTS;

CREATE TABLE "BLOCKINDEX"."BLOCKINDEX"
  (
    "ID"            NUMBER(19,0) NOT NULL ENABLE,
    "BLOCKHASH"     VARCHAR2(255 CHAR),
    "PREVBLOCKHASH"     VARCHAR2(255 CHAR),
    "FILENAME"      VARCHAR2(255 CHAR),
    "GENERATEDDATE" TIMESTAMP (6),
    "STARTFROMBYTE" NUMBER(19,0),
    PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "BLOCKINDEX_DB" ENABLE,
    CONSTRAINT "UK_BLOCKHASH" UNIQUE ("BLOCKHASH") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "BLOCKINDEX_DB" ENABLE
  )
  PARTITION BY RANGE("GENERATEDDATE") INTERVAL(NUMTOYMINTERVAL(1, 'MONTH'))
  SUBPARTITION BY hash("BLOCKHASH") SUBPARTITIONS 10
  (
    PARTITION before_FEB_2009 VALUES LESS THAN (TO_DATE('01-02-2009','dd-mm-yyyy'))
  )
PARALLEL;

