DROP TABLE "BLOCKINDEX"."BLOCKINDEX_TEMP";
CREATE TABLE "BLOCKINDEX"."BLOCKINDEX_TEMP"
  (
    "ID"            NUMBER(19,0) NOT NULL ENABLE,
    "CREATEDAT"     TIMESTAMP (6),
    "UPDATEDAT"     TIMESTAMP (6),
    "VERSION"       NUMBER(19,0),
    "BLOCKHASH"     VARCHAR2(255 CHAR),
    "FILENAME"      VARCHAR2(255 CHAR),
    "GENERATEDDATE" TIMESTAMP (6),
    "STARTFROMBYTE" NUMBER(19,0),
    PRIMARY KEY ("ID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "BLOCKINDEX" ENABLE,
    CONSTRAINT "UK_BLOCKHASH" UNIQUE ("BLOCKHASH") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "BLOCKINDEX" ENABLE
  )
  PARTITION BY RANGE
  (
    GENERATEDDATE
  )
  (
    PARTITION bh_2009 VALUES LESS THAN (to_date('01/01/2009','DD/MM/YYYY')) TABLESPACE BLOCKINDEX,
    PARTITION bh_2010 VALUES LESS THAN (to_date('01/01/2010','DD/MM/YYYY')) TABLESPACE BLOCKINDEX,
    PARTITION bh_2011 VALUES LESS THAN (to_date('01/01/2011','DD/MM/YYYY')) TABLESPACE BLOCKINDEX,
    PARTITION bh_2012 VALUES LESS THAN (to_date('01/01/2012','DD/MM/YYYY')) TABLESPACE BLOCKINDEX,
    PARTITION bh_2013 VALUES LESS THAN (to_date('01/01/2013','DD/MM/YYYY')) TABLESPACE BLOCKINDEX,
    PARTITION bh_2014 VALUES LESS THAN (to_date('01/01/2014','DD/MM/YYYY')) TABLESPACE BLOCKINDEX,
    PARTITION bh_2015 VALUES LESS THAN (to_date('01/01/2015','DD/MM/YYYY')) TABLESPACE BLOCKINDEX,
    PARTITION bh_2016 VALUES LESS THAN (to_date('01/01/2016','DD/MM/YYYY')) TABLESPACE BLOCKINDEX,
    PARTITION bh_2017 VALUES LESS THAN (to_date('01/01/2017','DD/MM/YYYY')) TABLESPACE BLOCKINDEX,
    PARTITION bh_2018 VALUES LESS THAN (to_date('01/01/2018','DD/MM/YYYY')) TABLESPACE BLOCKINDEX
  );
