DROP TABLE "BLOCKINDEX"."TRANSACTION" CASCADE CONSTRAINTS;
CREATE TABLE "BLOCKINDEX"."TRANSACTION"
  (
    "TRANSACTIONID"   NUMBER(19,0) NOT NULL ENABLE,
    "INPUTSUM"        NUMBER(19,0),
    "OUTPUTSUM"       NUMBER(19,0),
    "TRANSACTIONHASH" VARCHAR2(255 CHAR),
    "BLOCKID"         NUMBER(19,0) NOT NULL,
    CONSTRAINT "FK_BLOCKID" FOREIGN KEY ("BLOCKID") REFERENCES "BLOCKINDEX"."BLOCKINDEX" ("ID") ENABLE,
    PRIMARY KEY ("TRANSACTIONID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "BLOCKINDEX_DB" ENABLE
  )
  partition BY REFERENCE
  (
    FK_BLOCKID
  ) PARALLEL;
