CREATE TABLE "BLOCKINDEX"."TRANSACTION";

CREATE TABLE "BLOCKINDEX"."TRANSACTION_TEMP"
  (
    "TRANSACTIONID"    NUMBER(19,0) NOT NULL ENABLE,
    "INPUTSUM"        NUMBER(19,0),
    "OUTPUTSUM"       NUMBER(19,0),
    "TRANSACTIONHASH" VARCHAR2(255 CHAR),
    "BLOCKID"         NUMBER(19,0),
    PRIMARY KEY ("TRANSACTIONID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "BLOCKINDEX" ENABLE,
    CONSTRAINT "FK_BLOCKID" FOREIGN KEY ("BLOCKID") REFERENCES "BLOCKINDEX"."BLOCKINDEX_TEMP" ("ID") ENABLE
  ) PARTITION BY HASH
  (
    TRANSACTIONID
  )
  (
    PARTITION TI TABLESPACE BLOCKINDEX,
    PARTITION T2 TABLESPACE BLOCKINDEX,
    PARTITION T3 TABLESPACE BLOCKINDEX,
    PARTITION T4 TABLESPACE BLOCKINDEX,
    PARTITION T5 TABLESPACE BLOCKINDEX,
    PARTITION T6 TABLESPACE BLOCKINDEX,
    PARTITION T7 TABLESPACE BLOCKINDEX,
    PARTITION T8 TABLESPACE BLOCKINDEX,
    PARTITION T9 TABLESPACE BLOCKINDEX,
    PARTITION T10 TABLESPACE BLOCKINDEX,
    PARTITION T11 TABLESPACE BLOCKINDEX,
    PARTITION T12 TABLESPACE BLOCKINDEX,
    PARTITION T13 TABLESPACE BLOCKINDEX,
    PARTITION T14 TABLESPACE BLOCKINDEX,
    PARTITION T15 TABLESPACE BLOCKINDEX,
    PARTITION T16 TABLESPACE BLOCKINDEX
  );
  
