DROP TABLE "BLOCKINDEX"."TRANSACTIONINPUT_TEMP";
/
CREATE TABLE "BLOCKINDEX"."TRANSACTIONINPUT_TEMP"
  (
    "INPUTID"      NUMBER(19,0) NOT NULL ENABLE,
    "ADDRESS"      VARCHAR2(255 CHAR),
    "COINS"        NUMBER(19,0),
    "TRANSACTIONID" NUMBER(19,0),
    PRIMARY KEY ("INPUTID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "BLOCKINDEX" ENABLE,
    CONSTRAINT "FK_TI_TRANSACTIONID" FOREIGN KEY ("TRANSACTIONID") REFERENCES "BLOCKINDEX"."TRANSACTION_TEMP" ("TRANSACTIONID") ENABLE
  )  PARTITION BY HASH
  (
    INPUTID
  )
  (
    PARTITION TII TABLESPACE BLOCKINDEX,
    PARTITION TI2 TABLESPACE BLOCKINDEX,
    PARTITION TI3 TABLESPACE BLOCKINDEX,
    PARTITION TI4 TABLESPACE BLOCKINDEX,
    PARTITION TI5 TABLESPACE BLOCKINDEX,
    PARTITION TI6 TABLESPACE BLOCKINDEX,
    PARTITION TI7 TABLESPACE BLOCKINDEX,
    PARTITION TI8 TABLESPACE BLOCKINDEX,
    PARTITION TI9 TABLESPACE BLOCKINDEX,
    PARTITION TI10 TABLESPACE BLOCKINDEX,
    PARTITION TI11 TABLESPACE BLOCKINDEX,
    PARTITION TI12 TABLESPACE BLOCKINDEX,
    PARTITION TI13 TABLESPACE BLOCKINDEX,
    PARTITION TI14 TABLESPACE BLOCKINDEX,
    PARTITION TI15 TABLESPACE BLOCKINDEX,
    PARTITION TI16 TABLESPACE BLOCKINDEX
  );
