DROP TABLE "BLOCKINDEX"."TRANSACTIONOUTPUT_TEMP";

CREATE TABLE "BLOCKINDEX"."TRANSACTIONOUTPUT_TEMP"
  (
    "OUTPUTID"     NUMBER(19,0) NOT NULL ENABLE,
    "ADDRESS"      VARCHAR2(255 CHAR),
    "COINS"        NUMBER(19,0),
    "TRANSACTIONID" NUMBER(19,0),
    PRIMARY KEY ("OUTPUTID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "BLOCKINDEX" ENABLE,
    CONSTRAINT "FK_TO_TRANSATIONID" FOREIGN KEY ("TRANSACTIONID") REFERENCES "BLOCKINDEX"."TRANSACTION_TEMP" ("TRANSACTIONID") ENABLE
  )
  PARTITION BY HASH
  (
    OUTPUTID
  )
  (
    PARTITION TOI TABLESPACE BLOCKINDEX,
    PARTITION TO2 TABLESPACE BLOCKINDEX,
    PARTITION TO3 TABLESPACE BLOCKINDEX,
    PARTITION TO4 TABLESPACE BLOCKINDEX,
    PARTITION TO5 TABLESPACE BLOCKINDEX,
    PARTITION TO6 TABLESPACE BLOCKINDEX,
    PARTITION TO7 TABLESPACE BLOCKINDEX,
    PARTITION TO8 TABLESPACE BLOCKINDEX,
    PARTITION TO9 TABLESPACE BLOCKINDEX,
    PARTITION TO10 TABLESPACE BLOCKINDEX,
    PARTITION TO11 TABLESPACE BLOCKINDEX,
    PARTITION TO12 TABLESPACE BLOCKINDEX,
    PARTITION TO13 TABLESPACE BLOCKINDEX,
    PARTITION TO14 TABLESPACE BLOCKINDEX,
    PARTITION TO15 TABLESPACE BLOCKINDEX,
    PARTITION TO16 TABLESPACE BLOCKINDEX
  );