DROP TABLE "BLOCKINDEX"."TRANSACTIONOUTPUT" CASCADE CONSTRAINTS;

CREATE TABLE "BLOCKINDEX"."TRANSACTIONOUTPUT"
  (
    "OUTPUTID"     NUMBER(19,0) NOT NULL ENABLE,
    "ADDRESS"      VARCHAR2(255 CHAR),
    "COINS"        NUMBER(19,0),
    "TRANSACTIONID" NUMBER(19,0) NOT NULL,
    PRIMARY KEY ("OUTPUTID") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) TABLESPACE "BLOCKINDEX_DB" ENABLE,
    CONSTRAINT "FK_TO_TRANSATIONID" FOREIGN KEY ("TRANSACTIONID") REFERENCES "BLOCKINDEX"."TRANSACTION" ("TRANSACTIONID") ENABLE
  ) partition BY REFERENCE
  (
    FK_TO_TRANSATIONID
  ) PARALLEL;